### PR TITLE
library bumps

### PR DESCRIPTION
**Pull request by AndyScherzinger**
@stefan-niedermann sample app still working nicely 👍

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Thanks for the quick merge @stefan-niedermann - any chance for a lib release this week? Than I can bump the notes client.
No pressure though 🙏

**Comment by stefan-niedermann** [comment]
Yes, I'll try to make a release tomorrow (please remind me if not), but as mentioned, the conflict resolution seems to be the actual issue. Hope I can look at the solution because it likely affects also the Deck Android app 😉

**Comment by stefan-niedermann** [comment]
but the default gradlw rule *can't* be "take the lowest version", so maybe the order matters? have to dig into this...

**Comment by AndyScherzinger** [comment]
Thanks a lot for the release, bumped the Notes client main/stable branches 👍

**Pull request merged**
