### PR TITLE
Add support for image prefixes

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Successor of  #95 based on the work of @newhinton 

- [x] Ensure that we still request a preview version (send `x` and `y` query parameters). This has previously handled by the `sso-glide` module. I suggest to implement this feature also there for requests to the Notes API (`AbstractStreamFetcher`) as soon as we know how exactly the endpoint will look like.

### CODE REVIEW

**Comment by newhinton** [comment]
Oh this is better than what i did, especially since you wrote tests :D

However, i dont quite see how the x&y parameters are useful, the proposed attachement-api should be "general purpose", right? That means those parameters are superfluous for eg. pdf's. 

I mean the api can just handle that, but to me the whole idea of a size attribute seems just like a huge burden in terms of long term maintenance, with very little benefit. Wouldn't it be easier to just not differentiate and allways request the file "as is"? Where do you see the benefit that i might be missing?

**Comment by stefan-niedermann** [comment]
I orientated on the `preview` API of the files app. For image files the server will optionally deliver (and cache) a downscaled version to save bandwidth. User who need the whole image can just skip the `x` and `y` arguments. For mobile apps (think of 3G networks and limited mobile data) it is essentially important to not always fetch a 6 MB photo. For other file types which can not be downscaled, the API will simply ignore those parameters.

See also https://github.com/nextcloud/notes/issues/826#issuecomment-1206832073

**Comment by stefan-niedermann** [comment]
> Oh this is better than what i did, especially since you wrote tests :D

It's entirely based on your work, just some additions (and a f*cked up git history, but I'll fix this later) - so thank you 😄!

We just need to get [the public API](https://github.com/nextcloud/notes/issues/826) officially in, then we can continue here 🙂

**Comment by newhinton** [comment]
@stefan-niedermann Is this still good to go? If we get this merged, i can extend the notes app to use the proper server-api

**Comment by stefan-niedermann** [comment]
I have to recheck the current state of this PR, but in general I would be happy to eventually merge it.

To be honest, I was waiting about the integration of the new Rich Editor by Nextcloud but it looks like they did not even have a look at the existing editor attachment implementation. For example the Links to attachments are different if I recall correctly and I am not entirely sure that the attachment endpoint of the Notes server app has been finalized (and does also support attachments uploaded with the Rich Editor)

**Comment by newhinton** [comment]
Oh yeah. The rich text editor. Lets just say, i'm not a fan 😂

Though regardless of how the server actually does stuff, isn't this PR a bit independent of that? This should only enable that prefixes can be set at all, how and which should be handled by the actual app, or am i missing something?

I will have a but time later, and i'll gladly check how the richtext editor handles images. I seriously hope they dont do something weird with the paths.

**Comment by newhinton** [comment]
Okay, the path created by the rte is relative aswell. It creates an attachment folder where the images/files are stored. this is basically the same to the regular editor. That means we can reuse the same api for files edited for both editor types.

**Comment by newhinton** [comment]
Any news on this? I dont see anything that would blokc this and its companion PR in the notes app to move forward.

**Comment by stefan-niedermann** [comment]
@newhinton very sorry about the delay. Can you rebase on the current `master` please? I'll try review and merge it this year...

**Comment by stefan-niedermann** [comment]
Merged via #243 - sorry for the delay

**Pull request closed without merging**
